name: Create a release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: debug
        run: |
          echo -------
          ls -a 
          echo -------
          ls ../ -a

      - name: Create release version Issue
        uses: imjohnbo/issue-bot@v3
        with:
          labels: "RELEASE, ${{ github.ref }}"
          title: "RELEASE ${{ github.ref }}"
          body: |
            Author: ${{ github.actor }}
            Date: ${{ github.event.commits[0].timestamp }}
            Version: ${{ github.ref }}
            Changelog: ${{ steps.changelog.outputs.changes }}
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: nashmaniac/create-issue-action@v1.2
      #   name: Create Issue Action
      #   with:
      #     title: Release ${{ github.ref }}
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     assignees: ${{github.actor}}
      #     labels: RELEASE
      #     body: Workflow failed for commit ${{github.sha}}

  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: ${{ steps.changelog.outputs.changes }}
  #         draft: false
  #         prerelease: false
