name: releasing
run-name: Create a release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  issue:
    permissions:
      issues: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          includeInvalidCommits: true
          excludeTypes: other

      - name: Create registry issue
        uses: imjohnbo/issue-bot@v3
        with:
          labels: "RELEASE, ${{ github.ref_name }}"
          title: "RELEASE ${{ github.ref_name }}"
          body: |
            Author: ${{ github.actor }}
            Date: ${{ github.event.commits[0].timestamp }}
            Version: ${{ github.ref_name }}
            Changelog: ${{ steps.changelog.outputs.changes }}
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false
