name: Run unit and integration tests

on: [push, pull_request, workflow_dispatch]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npm test

            - name: Install browsers for playwright
              run: npx playwright install

            - name: Run playwright tests
              run: npx playwright test --project=chromium-ci

            - name: Archive code coverage results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
